{/*
The Dark Blue CyberPatriot Training Tool
Copyright (C) 2021 Scott Semian <darkbluedev@gmail.com>

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
*/}

import React, { Component } from 'react';
import './css/Style.css';
import Button from '@material-ui/core/Button';
import ProgramField from '../components/ProgramFields.jsx';
import { setJSONAttribute, getJSONAttribute } from '../components/jsonFileEditor.jsx';


export default class Packages extends Component {

    constructor(props) {
        super(props);

        this.state = {
            packages: []
        }
    }

    componentDidMount() {
        this.load();
    }

    componentWillUnmount() {
        this.save();
    }


    addPackage = (e) => {
        console.log("Adding a new package.");
        this.setState((prevState) => ({
            packages: [...prevState.packages, { index: Math.random(), name: "", installed: false, desired: false, positive_points: 0, negative_points: 0 }],
        }));
    }

    removePackage = (e) => {
        console.log("Removing package with index: " + e.index);
        this.setState({
            packages: this.state.packages.filter(p => p.index !== e.index)
        })
    }

    handleChange = (e) => {
        let idx = e.target.id.split('-')[1];
        if (e.target.name === "name") {
            let packages = [...this.state.packages]
            packages[idx][e.target.name] = e.target.value;
        }

        if (["positive_points", "negative_points"].includes(e.target.name)) {
            let packages = [...this.state.packages]
            packages[idx][e.target.name] = parseInt(e.target.value, 10);
        }

        if (e.target.name === "installed" || e.target.name === "desired") {
            let packages = [...this.state.packages]
            packages[idx][e.target.name] = !packages[idx][e.target.name];
        }
    }


    save = () => {
        console.log("Printing package values.");
        console.log(this.state.packages);
        setJSONAttribute("packages", this.state.packages);
    }

    load = () => {
        console.log("Attempting to load packages from JSON.");
        var isEmpty = false;
        var isNull = false;
        var data = getJSONAttribute('packages');

        if (data === undefined)
            isNull = true;

        if (!isNull && Object.keys(data).length === 0)
            isEmpty = true;

        if (!isEmpty && !isNull) {
            this.setState({ packages: data }, () => {
            });
        }
        else if (isEmpty || isNull) {
            this.setState({ packages: [{ index: Math.random(), name: "", installed: false, desired: false, positive_points: 0, negative_points: 0 }] })
        }
        return;
    }

    render() {
        return (
            <div className="page-div">
                <div className="page-header" >
                    <h1>Installed packages</h1>
                </div>
                <div className="page-info">
                    <p>
                        Package name: Name of the package that will be searched for.
                        <br></br>
                        Installed: If the package is installed when the scoring engine is started.
                        <br></br>
                        Desired: If the package is supposed to be installed.
                        <br></br>
                        Note: In order for a package to be scored, it <b>MUST</b> appear in the list generated by 'dpkg -l'.
                    </p>
                </div>
                <div className="page-body" >
                    <table style={{ width: '100%' }}>
                        <tbody>
                            <tr>
                                <th>Package Name</th>
                                <th>Installed</th>
                                <th>Desired</th>
                                <th>Positive Points</th>
                                <th>Negative Points</th>
                            </tr>
                            <ProgramField delete={this.removePackage} programs={this.state.packages} onChange={this.handleChange}></ProgramField>
                        </tbody>
                    </table>
                    <Button variant="contained" onClick={this.addPackage} onChange={this.handleChange} > Add Package </Button>
                    <Button variant="contained" onClick={this.save} style={{ marginLeft: '200px' }}> Save </Button>
                </div>
            </div >);
    }
}
